# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.12.0
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=776277928065bdd700e7433b97d9593b8b3b02e5a96c61b99f0ea908b59adf3b
# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli
# Start: Build Lifecycle
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "Smoking"
  - git config user.email "287482894@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${GITHUB_ACCESS_TOKEN}@${GH_REF}" master:master 
env:
 global:
   # Github Pages
   - GH_REF: github.com/Smoking/smoking.github.io.git


# End: Build LifeCycle
